name: Docker

on: push

jobs:
  node-docker:
    runs-on: ubuntu-20.04
    container:
      image: 14-buster-slim
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
