name: Docker

on: push

jobs:
  node-docker:
    runs-on: ubuntu-20.04
    container: node:14-alpine3.16
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
